# Generated by Django 3.1.5 on 2021-01-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20210117_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='title',
        ),
    ]
